#: pylint:skip-file
hotkeys:
  x_hotkeys:
    play_pause: XF86AudioPlay
    next: XF86AudioNext
    prev: XF86AudioPrev


clay_settings:
  x_keybinds: false

play_settings:
  authtoken: ""
  device_id: ""
  download_tracks: false
  password: ""
  username: ""
